// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pTd-UH_dQdKozF992-K2s_aOzbR_qnc',
    appId: '1:704372666556:web:268c67b81c06676e9260b9',
    messagingSenderId: '704372666556',
    projectId: 'milu-c4540',
    authDomain: 'milu-c4540.firebaseapp.com',
    storageBucket: 'milu-c4540.appspot.com',
    measurementId: 'G-D4ZDZW38B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2Dk-YAUomHR2K4RKcb8Wtm2LKcsf0po',
    appId: '1:704372666556:android:05717cee2ba29f189260b9',
    messagingSenderId: '704372666556',
    projectId: 'milu-c4540',
    storageBucket: 'milu-c4540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbEEPr9kHRI6gT18vXEqtulGPWQL8xTo',
    appId: '1:704372666556:ios:e26c8c70b0d3cc319260b9',
    messagingSenderId: '704372666556',
    projectId: 'milu-c4540',
    storageBucket: 'milu-c4540.appspot.com',
    iosBundleId: 'com.milu.milu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbEEPr9kHRI6gT18vXEqtulGPWQL8xTo',
    appId: '1:704372666556:ios:e7405324b50704b59260b9',
    messagingSenderId: '704372666556',
    projectId: 'milu-c4540',
    storageBucket: 'milu-c4540.appspot.com',
    iosBundleId: 'com.example.miluTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9pTd-UH_dQdKozF992-K2s_aOzbR_qnc',
    appId: '1:704372666556:web:e118b67818dca0b09260b9',
    messagingSenderId: '704372666556',
    projectId: 'milu-c4540',
    authDomain: 'milu-c4540.firebaseapp.com',
    storageBucket: 'milu-c4540.appspot.com',
    measurementId: 'G-566V69TM6S',
  );
}
